name: CI

on: [ push, pull_request ]

env:
  # Enable format attributes in ncurses headers
  # Enable fortified memory/string handling
  CPPFLAGS: -DGCC_PRINTF -DGCC_SCANF -D_FORTIFY_SOURCE=2

jobs:
  build-ubuntu-latest-minimal-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get install --no-install-recommends libncursesw5-dev
    - name: Bootstrap
      run: cd deb_generation/htop/ && ./autogen.sh
    - name: Configure
      run: cd deb_generation/htop/ && ./configure --enable-werror --enable-affinity --disable-unicode --disable-sensors
    - name: Build
      run: cd deb_generation/htop/ && make -k
    - name: Distcheck
      run: cd deb_generation/htop/ && make distcheck DISTCHECK_CONFIGURE_FLAGS="--enable-werror --enable-affinity --disable-unicode --disable-sensors"

  build-ubuntu-latest-minimal-clang:
    runs-on: ubuntu-latest
    env:
      CC: clang-15
    steps:
    - uses: actions/checkout@v4
    - name: install clang repo
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main' -y
        sudo apt-get update -q
    - name: Install Dependencies
      run: sudo apt-get install --no-install-recommends clang-15 libncursesw5-dev
    - name: Bootstrap
      run: cd deb_generation/htop/ && ./autogen.sh
    - name: Configure
      run: cd deb_generation/htop/ && ./configure --enable-werror --enable-affinity --disable-unicode --disable-sensors
    - name: Build
      run: cd deb_generation/htop/ && make -k
    - name: Distcheck
      run: cd deb_generation/htop/ && make distcheck DISTCHECK_CONFIGURE_FLAGS="--enable-werror --enable-affinity --disable-unicode --disable-sensors"

  build-ubuntu-latest-full-featured-gcc:
    runs-on: ubuntu-latest
    # Enable LTO, might trigger additional warnings on advanced inlining
    env:
      CFLAGS: -O3 -g -flto
      LDFLAGS: -O3 -g -flto -Wl,--as-needed
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get install --no-install-recommends libncursesw5-dev libhwloc-dev libnl-3-dev libnl-genl-3-dev libsensors4-dev libcap-dev
    - name: Bootstrap
      run: cd deb_generation/htop/ && ./autogen.sh
    - name: Configure
      run: cd deb_generation/htop/ && ./configure --enable-werror --enable-openvz --enable-vserver --enable-ancient-vserver --enable-unicode --enable-hwloc --enable-delayacct --enable-sensors --enable-capabilities
    - name: Build
      run: cd deb_generation/htop/ && make -k
    - name: Distcheck
      run: cd deb_generation/htop/ && make distcheck DISTCHECK_CONFIGURE_FLAGS='--enable-werror --enable-openvz --enable-vserver --enable-ancient-vserver --enable-unicode --enable-hwloc --enable-delayacct --enable-sensors --enable-capabilities'

  build-ubuntu-latest-full-featured-clang:
    runs-on: ubuntu-latest
    env:
      CC: clang-15
    steps:
    - uses: actions/checkout@v4
    - name: install clang repo
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main' -y
        sudo apt-get update -q
    - name: Install Dependencies
      run: sudo apt-get install --no-install-recommends clang-15 libncursesw5-dev libhwloc-dev libnl-3-dev libnl-genl-3-dev libsensors4-dev libcap-dev
    - name: Bootstrap
      run: cd deb_generation/htop/ && ./autogen.sh
    - name: Configure
      run: cd deb_generation/htop/ && ./configure --enable-werror --enable-openvz --enable-vserver --enable-ancient-vserver --enable-unicode --enable-hwloc --enable-delayacct --enable-sensors --enable-capabilities
    - name: Build
      run: cd deb_generation/htop/ && make -k
    - name: Distcheck
      run: cd deb_generation/htop/ && make distcheck DISTCHECK_CONFIGURE_FLAGS='--enable-werror --enable-openvz --enable-vserver --enable-ancient-vserver --enable-unicode --enable-hwloc --enable-delayacct --enable-sensors --enable-capabilities'

  build-ubuntu-latest-gcc-static:
    runs-on: ubuntu-latest
    # Enable LTO, might trigger additional warnings on advanced inlining
    env:
      CFLAGS: -O3 -g -flto
      LDFLAGS: -O3 -g -flto
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get install --no-install-recommends libncursesw5-dev libtinfo-dev libgpm-dev libsensors4-dev libcap-dev
    - name: Bootstrap
      run: cd deb_generation/htop/ && ./autogen.sh
    - name: Configure
      run: cd deb_generation/htop/ && ./configure --enable-static --enable-werror --enable-openvz --enable-vserver --enable-ancient-vserver --enable-unicode --disable-hwloc --disable-delayacct --enable-sensors --enable-capabilities
    - name: Build
      run: cd deb_generation/htop/ && make -k
    - name: Distcheck
      run: cd deb_generation/htop/ && make distcheck DISTCHECK_CONFIGURE_FLAGS='--enable-static --enable-werror --enable-openvz --enable-vserver --enable-ancient-vserver --enable-unicode --disable-hwloc --disable-delayacct --enable-sensors --enable-capabilities'

  build-ubuntu-latest-pcp:
    # we want PCP v5.2.3+
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get install --no-install-recommends libpcp3-dev libncursesw5-dev libtinfo-dev libgpm-dev
    - name: Bootstrap
      run: cd deb_generation/htop/ && ./autogen.sh
    - name: Configure
      run: cd deb_generation/htop/ && ./configure --enable-werror --enable-pcp --enable-unicode
    - name: Build
      run: cd deb_generation/htop/ && make -k

  build-ubuntu-latest-clang-analyzer:
    runs-on: ubuntu-latest
    env:
      CC: clang-15
    steps:
    - uses: actions/checkout@v4
    - name: install clang repo
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main' -y
        sudo apt-get update -q
    - name: Install Dependencies
      run: sudo apt-get install --no-install-recommends clang-15 clang-tools-15 libncursesw5-dev libnl-3-dev libnl-genl-3-dev libsensors4-dev libcap-dev
    - name: Bootstrap
      run: cd deb_generation/htop/ && ./autogen.sh
    - name: Configure
      run: cd deb_generation/htop/ && scan-build-15 -analyze-headers --status-bugs ./configure --enable-debug --enable-werror --enable-openvz --enable-vserver --enable-ancient-vserver --enable-unicode --enable-delayacct --enable-sensors --enable-capabilities
    - name: Build
      run: cd deb_generation/htop/ && scan-build-15 -analyze-headers --status-bugs make -j"$(nproc)"

  build-macos-latest-clang:
    runs-on: macOS-latest
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: brew install automake
    - name: Bootstrap
      run: cd deb_generation/htop/ && ./autogen.sh
    - name: Configure
      run: cd deb_generation/htop/ && ./configure --enable-werror
    - name: Build
      run: cd deb_generation/htop/ && make -k
    - name: Distcheck
      run: cd deb_generation/htop/ && make distcheck DISTCHECK_CONFIGURE_FLAGS="--enable-werror"
